name: hrid

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - wheel
  - ruamel.yaml
  - versioningit
  # testing
  - mypy
  - pre-commit
  - ruff
  - pytest
  - pytest-datadir
  - nox
