name: pytest using micromamba

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Update Python version in environment.yaml
      run: |
        sed -i '/^\s*-\s*python\s*$/ s/$/=${{ matrix.python-version }}/' environment.yaml
        echo "Updated environment.yaml content:"
        cat environment.yaml
    - name: Install environment with micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yaml
        cache-environment: true
    - name: Install hrid
      shell: bash -l {0}
      run: |
        python -m pip install -e ".[test]"
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        python -c "import hrid; print(hrid.__version__)"
        pytest
